{{- define "wg-config-template" -}}
[Interface]
Address = {{ .Values.wireguard.serverAddress }}
ListenPort = 51820
PostUp = wg set wg0 private-key /etc/wireguard/privatekey && iptables -t nat -A POSTROUTING -s {{ .Values.wireguard.serverCidr }} -o eth0 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -s {{ .Values.wireguard.serverCidr }} -o eth0 -j MASQUERADE

# Clients
{{- range .Values.wireguard.clients }}
[Peer]
{{- if .FriendlyName }}
# friendly_name = {{ .FriendlyName }}
{{- end }}
{{- if .FriendlyJson }}
# friendly_json = {{ .FriendlyJson | toJson }}
{{- end }}
PublicKey = {{ .PublicKey }}
AllowedIPs = {{ .AllowedIPs }}
{{- if .PresharedKey }}
PresharedKey = {{ .PresharedKey }}
{{- end }}

{{- end }}
# End Clients
{{- end -}}
{{- if and (not .Values.configSecretName) (not .Values.disableConfigManagement) }}
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-wg-config"
data:
  wg0.conf: {{ include "wg-config-template" . | b64enc }}
{{- end }}