name: Lint and Test Chart
on:
  workflow_dispatch:
  schedule:
    - cron:  '5 8 * * *'
  pull_request:
    paths:
      - 'helm/**'
jobs:
  test:
    name: 'Helm'
    uses: curium-rocks/flows/.github/workflows/helm-qa.yml@main
    with:
      charts_dir: 'helm'
      helm_extra_sets: '--set service.type=ClusterIP'
