name: Lint and Test Chart
on:
  workflow_dispatch:
  schedule:
    - cron:  '5 8 * * *'
  pull_request:
    paths:
      - 'helm/**'
      - '.github/workflows/helm-qa.yml'
jobs:
  test:
    strategy:
      matrix:
        suite:
          - name: default
            ct_extra_args: |
              --helm-extra-set-args='--set=service.type=ClusterIP'
    name: 'Helm (${{ matrix.suite.name }})'
    uses: curium-rocks/flows/.github/workflows/helm-qa.yml@main
    with:
      charts_dir: 'helm'
      ct_extra_args: ${{ matrix.suite.ct_extra_args }}
      run-kubeval: false
